// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqnlvetlxoxcizxahrpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xbmx2ZXRseG94Y2l6eGFocnBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMzQ4NTIsImV4cCI6MjA3MzcxMDg1Mn0.6JBYELumAcw3_QjTe6-LY-0nx-8S8D9phNFd-dKbFgU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});